version: '3.8'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.8.0'
    network_mode: "host"
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment: 
      - discovery.type=single-node

  packetbeat:
    image: 'docker.elastic.co/beats/packetbeat:7.8.0'
    user: 'packetbeat'
    network_mode: "host"
    volumes:
      - "./confs/packetbeat.docker.yml:/usr/share/packetbeat/packetbeat.yml"
    depends_on: 
      - elasticsearch
    cap_add:
      - NET_ADMIN
      - NET_RAW
